# Generated by Django 5.0.6 on 2026-07-02 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('offices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district_admins', to='offices.district'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active_staff',
            field=models.BooleanField(default=True, help_text='Toggle to suspend a staff account without deleting it (e.g. on leave).'),
        ),
        migrations.AddField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, help_text='Citizenship number or national ID, used to prevent duplicate bookings.', max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='offices.office'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('ne', 'Nepali')], default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('reception', 'Reception Staff'), ('operator', 'Counter Operator'), ('manager', 'Office Manager'), ('district_admin', 'District Administrator'), ('supervisor', 'Government Supervisor'), ('admin', 'System Administrator')], db_index=True, default='citizen', max_length=20),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'office'], name='accounts_us_role_e31a84_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'district'], name='accounts_us_role_c89b46_idx'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='accounts_user',
        ),
    ]
