# Generated by Django 5.0.6 on 2026-07-02 03:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(db_index=True, help_text="Short prefix used in token numbers for this service, e.g. 'PSP' -> PSP-001.", max_length=10)),
                ('description', models.TextField(blank=True)),
                ('required_documents', models.TextField(blank=True, help_text='Free-text list of documents citizens must bring.')),
                ('average_duration_minutes', models.PositiveIntegerField(default=10, help_text='Baseline service duration used for wait-time estimation until enough historical data exists.', validators=[django.core.validators.MinValueValidator(1)])),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('requires_appointment', models.BooleanField(default=False, help_text='If true, walk-ins are not allowed for this service.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='offices.office')),
            ],
            options={
                'db_table': 'services_service',
                'ordering': ['office', 'name'],
                'indexes': [models.Index(fields=['office', 'is_active'], name='services_se_office__749678_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('office', 'code'), name='unique_service_code_per_office'),
        ),
    ]
