# Generated by Django 5.0.6 on 2026-07-02 03:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text="e.g. 'Main Waiting Hall', 'Entrance'.", max_length=100)),
                ('source_type', models.CharField(choices=[('webcam', 'Local Webcam'), ('rtsp', 'RTSP Stream'), ('upload', 'Uploaded Video (testing)')], default='rtsp', max_length=10)),
                ('stream_url', models.CharField(blank=True, help_text='RTSP/HTTP URL, empty for local webcam index 0.', max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('detection_interval_seconds', models.PositiveIntegerField(default=10, help_text='How often the YOLO pipeline pulls and analyzes a frame from this feed.', validators=[django.core.validators.MinValueValidator(1)])),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='offices.office')),
            ],
            options={
                'db_table': 'crowd_ai_camera_feed',
                'ordering': ['office', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CrowdSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('people_count', models.PositiveIntegerField()),
                ('occupancy_percentage', models.DecimalField(decimal_places=2, help_text='people_count / office.capacity.max_capacity * 100, computed at capture time.', max_digits=5)),
                ('captured_at', models.DateTimeField(db_index=True)),
                ('annotated_frame', models.ImageField(blank=True, help_text='Frame with YOLO bounding boxes drawn, stored only for a rolling retention window.', null=True, upload_to='crowd_ai/snapshots/%Y/%m/%d/')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='crowd_ai.camerafeed')),
            ],
            options={
                'db_table': 'crowd_ai_snapshot',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='CrowdAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('alert_type', models.CharField(choices=[('overcrowding', 'Overcrowding'), ('camera_offline', 'Camera Offline')], db_index=True, max_length=20)),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('triggered_at', models.DateTimeField(db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='crowd_ai.camerafeed')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='crowd_ai.crowdsnapshot')),
            ],
            options={
                'db_table': 'crowd_ai_alert',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.AddIndex(
            model_name='crowdsnapshot',
            index=models.Index(fields=['camera', 'captured_at'], name='crowd_ai_sn_camera__da5bfd_idx'),
        ),
        migrations.AddIndex(
            model_name='crowdalert',
            index=models.Index(fields=['camera', 'resolved_at'], name='crowd_ai_al_camera__3f59ef_idx'),
        ),
    ]
