# Generated by Django 5.0.6 on 2026-07-02 03:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('province', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'offices_district',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('office_type', models.CharField(choices=[('passport', 'Passport Office'), ('transport', 'Transport Management Office'), ('municipality', 'Municipality Office'), ('ward', 'Ward Office'), ('inland_revenue', 'Inland Revenue Office'), ('land_revenue', 'Land Revenue Office'), ('hospital', 'Hospital'), ('psc', 'Public Service Commission Office')], db_index=True, max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('opening_time', models.TimeField(default='10:00')),
                ('closing_time', models.TimeField(default='17:00')),
                ('working_days', models.CharField(default='Sun,Mon,Tue,Wed,Thu', help_text='Comma-separated working days (Nepal government week: Sun-Thu, plus 1st/3rd Sat off).', max_length=50)),
                ('max_daily_tokens', models.PositiveIntegerField(default=200, help_text='Cap on tokens issued per day, to prevent overbooking beyond office capacity.', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offices', to='offices.district')),
            ],
            options={
                'db_table': 'offices_office',
                'ordering': ['district__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OfficeCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('max_capacity', models.PositiveIntegerField(help_text='Maximum comfortable occupancy of the waiting area.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5000)])),
                ('alert_threshold_percentage', models.PositiveIntegerField(default=85, help_text='Occupancy % at which a congestion alert is triggered.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('office', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capacity', to='offices.office')),
            ],
            options={
                'db_table': 'offices_office_capacity',
            },
        ),
        migrations.AddIndex(
            model_name='office',
            index=models.Index(fields=['office_type', 'district'], name='offices_off_office__143ca9_idx'),
        ),
        migrations.AddIndex(
            model_name='office',
            index=models.Index(fields=['is_active'], name='offices_off_is_acti_98433c_idx'),
        ),
        migrations.AddConstraint(
            model_name='office',
            constraint=models.UniqueConstraint(fields=('name', 'district'), name='unique_office_name_per_district'),
        ),
    ]
