# Generated by Django 5.0.6 on 2026-07-02 03:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('queue_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('shift_start', models.DateTimeField()),
                ('shift_end', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='queue_management.counter')),
                ('operator', models.ForeignKey(limit_choices_to={'role': 'operator'}, on_delete=django.db.models.deletion.CASCADE, related_name='counter_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'operators_counter_assignment',
                'ordering': ['-shift_start'],
                'indexes': [models.Index(fields=['operator', 'is_active'], name='operators_c_operato_1e045d_idx'), models.Index(fields=['counter', 'is_active'], name='operators_c_counter_55e816_idx')],
            },
        ),
        migrations.CreateModel(
            name='OperatorActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(choices=[('called', 'Called Next'), ('skipped', 'Skipped'), ('held', 'Put On Hold'), ('resumed', 'Resumed From Hold'), ('completed', 'Completed'), ('transferred', 'Transferred'), ('emergency', 'Marked Emergency'), ('cancelled', 'Cancelled'), ('no_show', 'Marked No Show')], db_index=True, max_length=15)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to=settings.AUTH_USER_MODEL)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='queue_management.token')),
            ],
            options={
                'db_table': 'operators_action_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['operator', 'action'], name='operators_a_operato_2c7bd1_idx'), models.Index(fields=['token', 'action'], name='operators_a_token_i_5fc4d1_idx')],
            },
        ),
    ]
