# Generated by Django 5.0.6 on 2026-07-02 03:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offices', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('granularity', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily')], db_index=True, max_length=10)),
                ('date', models.DateField(db_index=True)),
                ('hour', models.PositiveSmallIntegerField(blank=True, help_text='0-23, only set when granularity=hourly.', null=True)),
                ('tokens_issued', models.PositiveIntegerField(default=0)),
                ('tokens_completed', models.PositiveIntegerField(default=0)),
                ('tokens_cancelled', models.PositiveIntegerField(default=0)),
                ('tokens_no_show', models.PositiveIntegerField(default=0)),
                ('average_wait_minutes', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('average_service_minutes', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('max_queue_length', models.PositiveIntegerField(default=0)),
                ('average_satisfaction_score', models.DecimalField(blank=True, decimal_places=2, help_text='1.00-5.00, from post-service citizen feedback.', max_digits=3, null=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='offices.office')),
                ('service', models.ForeignKey(blank=True, help_text='Null means this row aggregates the whole office, not one service.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='services.service')),
            ],
            options={
                'db_table': 'analytics_queue_statistic',
                'ordering': ['-date', 'hour'],
                'indexes': [models.Index(fields=['office', 'granularity', 'date'], name='analytics_q_office__6f25df_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='queuestatistic',
            constraint=models.UniqueConstraint(fields=('office', 'service', 'granularity', 'date', 'hour'), name='unique_statistic_row'),
        ),
    ]
