# Generated by Django 5.0.6 on 2026-07-02 03:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offices', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('counter_number', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('on_break', 'On Break')], db_index=True, default='closed', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('current_operator', models.ForeignKey(blank=True, limit_choices_to={'role': 'operator'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_counters', to=settings.AUTH_USER_MODEL)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counters', to='offices.office')),
                ('services', models.ManyToManyField(blank=True, help_text='Services this counter is capable of handling.', related_name='counters', to='services.service')),
            ],
            options={
                'db_table': 'queue_counter',
                'ordering': ['office', 'counter_number'],
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('walk_in_name', models.CharField(blank=True, max_length=150)),
                ('walk_in_phone', models.CharField(blank=True, max_length=15)),
                ('token_number', models.CharField(db_index=True, help_text='Human-readable token, e.g. PSP-014. Unique per office per day.', max_length=20)),
                ('queue_date', models.DateField(db_index=True, help_text='The day this token is valid for.')),
                ('scheduled_time', models.TimeField(blank=True, help_text='Booked slot, for online bookings.', null=True)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('waiting', 'Waiting'), ('called', 'Called'), ('serving', 'Serving'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('transferred', 'Transferred')], db_index=True, default='booked', max_length=15)),
                ('source', models.CharField(choices=[('online', 'Online Booking'), ('walk_in', 'Walk-in')], default='online', max_length=10)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('priority', 'Priority (Senior Citizen / PWD)'), ('emergency', 'Emergency')], db_index=True, default='normal', max_length=10)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('serving_started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_wait_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('prediction_confidence', models.DecimalField(blank=True, decimal_places=1, help_text='0.0-100.0 confidence score from the wait-time prediction model.', max_digits=4, null=True)),
                ('notes', models.TextField(blank=True)),
                ('citizen', models.ForeignKey(blank=True, limit_choices_to={'role': 'citizen'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens', to=settings.AUTH_USER_MODEL)),
                ('counter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens', to='queue_management.counter')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tokens', to='offices.office')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tokens', to='services.service')),
            ],
            options={
                'db_table': 'queue_token',
                'ordering': ['queue_date', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='counter',
            index=models.Index(fields=['office', 'status'], name='queue_count_office__013413_idx'),
        ),
        migrations.AddConstraint(
            model_name='counter',
            constraint=models.UniqueConstraint(fields=('office', 'counter_number'), name='unique_counter_number_per_office'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['office', 'queue_date', 'status'], name='queue_token_office__b27967_idx'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['service', 'queue_date', 'status'], name='queue_token_service_c7a859_idx'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['counter', 'status'], name='queue_token_counter_d8bf44_idx'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['citizen', 'queue_date'], name='queue_token_citizen_8ace1a_idx'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['priority', 'status'], name='queue_token_priorit_63c211_idx'),
        ),
        migrations.AddConstraint(
            model_name='token',
            constraint=models.UniqueConstraint(fields=('office', 'queue_date', 'token_number'), name='unique_token_per_office_per_day'),
        ),
    ]
