# Generated by Django 5.0.6 on 2026-07-02 03:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('queue_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], db_index=True, max_length=10)),
                ('event_type', models.CharField(choices=[('token_booked', 'Token Booked'), ('reminder', 'Reminder'), ('queue_approaching', 'Queue Approaching'), ('now_serving', 'Now Serving'), ('counter_changed', 'Counter Changed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, max_length=25)),
                ('recipient', models.CharField(help_text='Phone number or email address at time of sending.', max_length=150)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='queue_management.token')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='notificatio_user_id_dec749_idx'), models.Index(fields=['token', 'event_type'], name='notificatio_token_i_c12c76_idx')],
            },
        ),
    ]
