# Generated by Django 5.0.6 on 2026-07-02 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='event_type',
            field=models.CharField(choices=[('token_booked', 'Token Booked'), ('reminder', 'Reminder'), ('queue_approaching', 'Queue Approaching'), ('now_serving', 'Now Serving'), ('counter_changed', 'Counter Changed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('otp_verification', 'OTP Verification')], db_index=True, max_length=25),
        ),
    ]
